clear all; close all; clc;
load('./transfer_euler/T_list_Euler.mat', 'T_list');
load('./transfer_euler/loss_list_Euler.mat', 'loss_list');
T_list_E = T_list;
loss_list_E = loss_list;
load('./transfer_vi/T_list_VI.mat', 'T_list');
load('./transfer_vi/loss_list_VI.mat', 'loss_list');
T_list_V = T_list;
loss_list_V = loss_list;
load('./transfer_pmi/T_list_PMI.mat', 'T_list');
load('./transfer_pmi/loss_list_PMI.mat', 'loss_list');
T_list_P = T_list;
loss_list_P = loss_list;

semilogx(T_list_V(2:end),loss_list_V(2:end));
hold on;
semilogx(T_list_E(2:end), loss_list_E(2:end));
hold on;
semilogx(T_list_P(2:end), loss_list_P(2:end));
legend('variational', 'Euler', 'PMI');
xlabel('time step size, [s]');
ylabel('loss');
ylim([0, 0.1]);
hold on;
